### ISSUE TITLE
NPI - менеджер пакетов и магазин приложений

### ISSUE THREAD

**Issue by PROPHESSOR** [JsOS-Team/JsOS#11]
**NPI** будет использоваться для установки, удаления и обновления пакетов, а так же (в будущем) как магазин приложений.

**Comment by imachug** [comment]
Если сделать поддержку сети, можно будет запилить репозиторий в вебе (как apt) и оттуда качать пакеты.

**Comment by imachug** [comment]
@PROPHESSOR У меня http не зашел. Хотя, может нужно QEMU настроить?

**Comment by imachug** [comment]
```bash
$ node .
Listening on port 2968
```

Открываю в браузере `gui/index.html`. Вписываю 2968.

**Comment by PROPHESSOR** [comment]
@imachug проверь dns google.com

**Comment by imachug** [comment]
DNS работает. WGET - нет.

**Comment by PROPHESSOR** [comment]
@imachug ну вот, значит проблема не в QEMU/Virtio/драйвере, а в api...

**Comment by usernameak** [comment]
у нас не до конца сделана поддержка TCP протокола

**Comment by PROPHESSOR** [comment]
@usernameak вроде бы, она даже сделана...
Просто делалась тремя людьми в разное время... Из-за этого очень кривая...

**Comment by imachug** [comment]
@PROPHESSOR Может и сделана, но http глючит. DNS работает, а HTTP - нет.

**Comment by imachug** [comment]
Npi - это NodeJS package injector?

**Comment by PROPHESSOR** [comment]
@imachug Хех, нет)
No Problem Installer

**Comment by PROPHESSOR** [comment]
У меня на linux такая штука стоит
```npi vim``` И vim установлен

**Comment by imachug** [comment]
HTTP пока это блочит. Нашел баг в eshttp, пожалуй, можно форкнуть https://github.com/iefserge/eshttp и задать свой форк как dependency.

**Comment by imachug** [comment]
Если будут какие-то вопросы, надо писать в https://github.com/JsOS-Team/NPI-pkg/
