### ISSUE TITLE
Поддерживаю идею 5 конечностями

### ISSUE THREAD

**Issue by itween** [JsOS-Team/JsOS#32]
Если нужны идеи, то могу набросать

**Comment by PROPHESSOR** [comment]
Новые мысли и идеи - всегда хорошо ;)

**Comment by PROPHESSOR** [comment]
Ну хорошо, какие идеи?

**Comment by Milk-Cool** [comment]
> Ну хорошо, какие идеи?

https://github.com/JsOS-Team/JsOS/issues/64
