### ISSUE TITLE
Ошибка kernel

### ISSUE THREAD

**Issue by ivan770** [JsOS-Team/JsOS#42]
Uncaught exception: __loader:25: Error: Cannot resolve module 'module-singleton' from '/js/index.js'
Error: Cannot resolve module 'module-singleton' from '/js/index.js'
    at Module.require (__loader:202:24)
    at /js/index.js:60:69
    at /js/index.js:21:1
    at /js/index.js:60:28
    at Module.require (__loader:232:13)
    at Loader.require (__loader:250:27)
    at __loader:296:10
    at __loader:332:3
[ terminate thread (reason: refcount 0) ]
Kernel error: Assertion failed: !"main isolate exited" (/home/usernameak/jsos-git/src/kernel/thread.cc: TearDown: 117)

**Comment by PROPHESSOR** [comment]
Эм...
npm i выполнен?
И при каких действиях возникает эта ошибка?

**Comment by PROPHESSOR** [comment]
@usernameak что там делает твой путь?

**Comment by ivan770** [comment]
@PROPHESSOR ухх, про `npm i` забыл. Помогло, спасибо. Возникала ошибка если попытаться просто запустить OS только загруженой с репозитория

**Comment by usernameak** [comment]
@PROPHESSOR мой путь - из отладочной инфы которая при сборке создалась
