### ISSUE TITLE
Recommendation: Use --netdev virtio by default / Рекомендация: Использовать --netdev virtio по умолчанию

### ISSUE THREAD

**Issue by imachug** [JsOS-Team/JsOS#48]
--netdev has the default value of rtl8139, which may not be the correct model and probably won't work for many users. Passing `virtio` will fix this.

У --netdev значение по умолчанию - rtl8139, но у пользователя может быть другая модель, и сеть не заработает. `--netdev virtio` это исправит.

**Comment by imachug** [comment]
@PROPHESSOR @usernameak Хотел бы перенести в JsOS-Team/JsOS-CLI, но там закрыты Issues и я не collaborator.

**Comment by usernameak** [comment]
> Другая модель
Это тип **эмулируемой** сетевой карты

**Comment by imachug** [comment]
@usernameak Хм... Значит где-то в эмуляции ошибка. Я дебагал, оказалось, что последние ~4 байта у *всех* пакетов рандомные, поэтому приходят неверные данные, а при Content-Transfer: chunked эти 4 байта приходятся на размер чанка, драйвер парсит размер как NaN и никогда не доходит до конца.

**Comment by PROPHESSOR** [comment]
@imachug есть

**Comment by imachug** [comment]
@PROPHESSOR Спасибо.

**Comment by imachug** [comment]
https://github.com/JsOS-Team/JsOS-CLI/issues/1
