### ISSUE TITLE
Искусственный вызов "паники ядра"?

### ISSUE THREAD

**Issue by ivan770** [JsOS-Team/JsOS#50]
Глядя на свой прошлый коммит, я хочу сделать сообщение о необходимости ребута. Для теста необходимо сделать эту самую "панику ядра"

**Comment by imachug** [comment]
Паники как таковой нет. Есть `writeError`, который многие пакеты вызывают, а потом не возвращают в консоль через `res(0)`. И есть `throw new Error(...)`.

**Comment by PROPHESSOR** [comment]
Паника ядра есть

**Comment by ivan770** [comment]
Ну как сказать. К примеру, если вызвать любую ошибку node js, вся система требует рестарта

**Comment by usernameak** [comment]
В ядре kernel panic определен функцией `GLOBAL_boot_services()->FatalError("string")`, может экспортировать ее в JS?

**Comment by imachug** [comment]
Даешь больше паник! `throw new Error`, `writeError`, `FatalError`

**Comment by imachug** [comment]
WTFError к assert надо прикрутить :)
