### ISSUE TITLE
Зависание на старте

### ISSUE THREAD

**Issue by ivan770** [JsOS-Team/JsOS#52]
Приходится по несколько раз рестартать qemu, только для того чтобы заработала ОС
Логи ядра: https://gist.github.com/ivan770/0abd4a1ef88246a141d427f804406d9c
Скрин системы: 
![image](https://user-images.githubusercontent.com/14003886/38948287-cab0f86c-4347-11e8-9d6c-200f834722ea.png)

Предполагаю, но не уверен, что это из-за сети

**Comment by imachug** [comment]
Попробуйте `jsos start --netdev virtio`.

**Comment by ivan770** [comment]
Вроде помогло. Спасибо!

**Comment by PROPHESSOR** [comment]
[Сделал](https://github.com/JsOS-Team/JsOS-CLI/commit/b2c72d3712948ac7b7be04d099a90432a51c2116) virtio сетевым интерфейсом по умолчанию

**Comment by imachug** [comment]
@PROPHESSOR realtek еще не пофиксили?

**Comment by usernameak** [comment]
@imachug нет. Там ошибка переполнения, как я понял, но я не могу понять почему не срабатывает флаг WRAP
