### ISSUE TITLE
Запуск сети

### ISSUE THREAD

**Issue by ivan770** [JsOS-Team/JsOS#55]
На данный момент пишу утилиту для управления сетью, но есть одна проблема - включить собственно сеть! Пробовал менять стандартный драйвер и virtio, включал разные режимы в --net, ничего не помогло. Есть решение?

**Comment by imachug** [comment]
А что именно не работает?

**Comment by ivan770** [comment]
Полностью всё.

![image](https://user-images.githubusercontent.com/14003886/39087498-875e6ed6-45aa-11e8-8bc2-44d37acaa26c.png)

**Comment by ivan770** [comment]
Там на запуске выдаёт "Network card is not supported"

**Comment by imachug** [comment]
Гм... А qemu так и запускаете через `jsos start --netdev virtio`? Какие логи?

**Comment by ivan770** [comment]
https://pastebin.com/jg4gLUGg

**Comment by imachug** [comment]
Попробуйте `npm update eshttp`.

**Comment by ivan770** [comment]
Увы. Ошибка на запуске и неработающая сеть. Логи: https://pastebin.com/JxVp4B1J

**Comment by imachug** [comment]
@ivan770 А у Вас быстрое соединение? Судя по коду, `Your network card is not supported` выбрасывается по таймауту.

**Comment by ivan770** [comment]
@imachug 8.2 мб/с

**Comment by imachug** [comment]
Замените `}, 1000);` на `}, 1000000);` в строке 87 файла `js/component/dns-client/index.js`.

**Comment by ivan770** [comment]
@imachug вроде сработало. Спасибо!

**Comment by imachug** [comment]
Надо будет увеличить таймаут.
