### ISSUE TITLE
Running on the Windows. 

### ISSUE THREAD

**Issue by xilaraux** [JsOS-Team/JsOS#56]
I cannot run the project on my own PC(I'm using Windows).
Maybe someone faced this error? 

`--- starting qemu ---
OK!
Unexpected error in aio_context_set_poll_params() at /home/stefan/src/qemu/repo.or.cz/qemu/ar7/util/aio-win32.c:413:
qemu-system-x86_64: AioContext polling is not implemented on Windows

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`

**Comment by ivan770** [comment]
Как на Винде мог выйти такой путь?

**Comment by imachug** [comment]
@ivan770 Это вроде как путь машины, на которой компилировалось (билд-сервера). / Looks like it is build server's path.

**Comment by xilaraux** [comment]
@ivan770 Дело в том что я юзаю Bah под виндой, оттого и пути такие. 😀 
@imachug Правильно я понимаю, единственный вариант это делать все из-под линухи?

**Comment by ivan770** [comment]
@xilaraux эмм... Я под виндой запустил. qemu + прописывание PATH

**Comment by xilaraux** [comment]
@ivan770 можешь, пожалуйста, поподробнее?

**Comment by PROPHESSOR** [comment]
@xilaraux это ошибка в QEMU...
Попробуйте переустановить и убедитесь в том, что команда qemu-system-x86_64 открывает окно QEMU.

**Comment by xilaraux** [comment]
@PROPHESSOR верно. я буду разбираться уже с qemu.
