### ISSUE TITLE
Проблемы с получением MAC адреса

### ISSUE THREAD

**Issue by ivan770** [JsOS-Team/JsOS#57]
При попытке получение MAC адреса из модуля `/core/net/mac-address` возникает следующий результат: 
![default](https://user-images.githubusercontent.com/14003886/39204424-6a0c3cc0-4800-11e8-96df-580314a2f94f.png)

Брал результат из MACAddress.BROADCAST

**Comment by imachug** [comment]
Где-то еще надо искать. Broadcast - это всегда FF, даже в IPv4.

**Comment by PROPHESSOR** [comment]
Возможно, это из-за & 0xFF

**Comment by ivan770** [comment]
@imachug и вправду. Что-то я полез делать не почитав об этом...

**Comment by usernameak** [comment]
Broadcast MAC-адрес всегда FF
