### ISSUE TITLE
Ошибка qemu: socket_set_fast_reuse: Assertion `ret == 0' failed

### ISSUE THREAD

**Issue by Ghost-ate-your-brains** [JsOS-Team/JsOS#61]
Здравствуйте когда я ввожу jsos start
он мне высирает это:

user@ubuntu:~/JsOS$ sudo jsos start
 --- starting qemu --- 
OK!
qemu-system-x86_64: /build/qemu-Q8WXNl/qemu-2.11+dfsg/util/oslib-posix.c:180: socket_set_fast_reuse: Assertion `ret == 0' failed.
Aborted (core dumped)

**Comment by Keneshin** [comment]
А зачем sudo?

**Comment by Ghost-ate-your-brains** [comment]
> А зачем sudo?
> 

Ты мне пишешь год спустя?🤣 Хер знает что в башке было

**Comment by Ghost-ate-your-brains** [comment]
> А зачем sudo?
> 

Но даже если запустил с судо не из-за этого ошибка)

**Comment by Keneshin** [comment]
Ну, я ошибку на данный момент повторить не могу, значит её скорее всего пофиксили, и issue можно закрывать

**Comment by Ghost-ate-your-brains** [comment]
> Ну, я ошибку на данный момент повторить не могу, значит её скорее всего пофиксили, и issue можно закрывать

Да кншн, по правде я и забыл про свою issue
