### ISSUE TITLE
Сборка .iso

### ISSUE THREAD

**Issue by Milk-Cool** [JsOS-Team/JsOS#63]
Здравствуйте!

Хотел бы записать модифицированную JsOS на флешку (для теста ещё на другую виртуалку). Как я могу сгенерировать .iso-файл?

Заранее спасибо!

**Comment by Milk-Cool** [comment]
Попробовал `jsos mkiso`

Откуда установить "grub-mkrescue"? Пробовал из apt и npm.

**Comment by Milk-Cool** [comment]
Нашёл! Установил grub-common и xorriso. Выводит ошибку:

`Let's start to create the ISO image =)
 --- creating image --- 
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

xorriso : FAILURE : -as mkisofs: Cannot accept directory as target: -o '.'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
grub-mkrescue: ошибка: `xorriso` invocation failed
.
OK!`

Пишет "ОК!", но .iso я не нашёл...

**Comment by Milk-Cool** [comment]
Я понял! Вместо директории надо было указывать файл... (фейспалм)

**Comment by Milk-Cool** [comment]
Не получилось. Определяется как "неправильно секторированный" (сам подозреваю, что такого слова нет).

**Comment by PROPHESSOR** [comment]
А этот .iso работает?
https://github.com/JsOS-Team/JsOS/releases/tag/0.2.0

**Comment by Milk-Cool** [comment]
Нет. Ни на одном из доступных компьютеров.
(извините за поздный ответ, учёба.)

**Comment by PROPHESSOR** [comment]
Значит проблема на этапе записи образа.

**Comment by Milk-Cool** [comment]
Буду пробовать другие программы, спасибо.

**Comment by Milk-Cool** [comment]
А какой программой вы пользовались? (Надеюсь, что пользовались.)
Я час ничего не могу найти.

**Comment by imachug** [comment]
`dd`

**Comment by Milk-Cool** [comment]
Не, не работает :(

**Comment by PROPHESSOR** [comment]
На флешку ставил через
https://unetbootin.github.io
