### ISSUE TITLE
Что-то странное при генерации .iso

### ISSUE THREAD

**Issue by Milk-Cool** [JsOS-Team/JsOS#65]
Сгенерированный ISO показывает GRUB - это нормально? Как запустить систему?

**Comment by usernameak** [comment]
Я даже не уверен, работает ли оно.

**Comment by Milk-Cool** [comment]
Я пишу `sudo jsos mkiso out.iso`

Вывод:
```
Let's start to create the ISO image =)
 --- creating image --- 
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:out.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 37.3g free
Added to ISO image: directory '/'='/tmp/grub.OWrtz3'
xorriso : UPDATE :     290 files added in 1 seconds
Added to ISO image: directory '/'='/home/user/JsOS/undefined'
xorriso : UPDATE :     290 files added in 1 seconds
xorriso : NOTE : Copying to System Area: 512 bytes from file '/usr/lib/grub/i386-pc/boot_hybrid.img'
ISO image produced: 2479 sectors
Written to medium : 2479 sectors at LBA 0
Writing to 'stdio:out.iso' completed successfully.

OK!
```

Прошу обратить внимание на `/home/user/JsOS/undefined`. Судя по всему, это так быть не должно. Что с этим делать? Официального гайда по сборке нет.

**Comment by Milk-Cool** [comment]
Попробовал ещё `jsos mkiso out.iso .`. Вроде бы всё хорошо, но всё ещё показывает GRUB вместо загрузки в систему.

**Comment by Milk-Cool** [comment]
![Снимок экрана от 2021-08-02 16-40-42](https://user-images.githubusercontent.com/43724263/127871126-3e2c8c74-7645-426e-a7b0-1e11dff179d8.png)

**Comment by Keneshin** [comment]
Проблема скорее всего в CLI, а не в самой системе

**Comment by Milk-Cool** [comment]
> Проблема скорее всего в CLI, а не в самой системе

Вы имеете в виду JsOS-CLI? (Просто не уверен)

**Comment by Keneshin** [comment]
Да, я имею в виду JsOS-CLI.
Исходники я тоже смотрел, но там ничего не понятно, надо детальнее рассматривать

**Comment by Milk-Cool** [comment]
Переношу issue [сюда](https://github.com/JsOS-Team/JsOS-CLI/issues)

**Comment by PROPHESSOR** [comment]
Забыл указать папку сборки
Попробуй

`jsos mkiso out.iso tmpbuildfolder`

**Comment by Milk-Cool** [comment]
> Забыл указать папку сборки
> Попробуй
> 
> `jsos mkiso out.iso tmpbuildfolder`

Получилось, спасибо
