### ISSUE TITLE
Assertion failed: !"No more physical pages to allocate."

### ISSUE THREAD

**Issue by Keneshin** [JsOS-Team/JsOS#69]
При запуске системы через `jsos start` вылезает вот это:
![изображение](https://user-images.githubusercontent.com/64722117/128048338-fa747784-0d31-45ae-a016-931b3ec481e2.png)

**Comment by Milk-Cool** [comment]
Удалите имяфайла.img файл, у меня сработало

**Comment by Keneshin** [comment]
Да, заработало, спасибо.

**Comment by Milk-Cool** [comment]
вау, я полезен
